% === Urban Coverage Simulation using Ray Tracing in Kitakyushu ===

% --- 1. Start site viewer (with or without OSM buildings) ---
% Pokud máš OSM soubor (např. kitakyushu.osm), odkomentuj následující řádek:
viewer = siteviewer(Buildings="map_kokura.osm", Basemap="topographic");

% --- 2. Define Transmitter Site (Base Station) ---
bs_lat = 33.88649129953387;
bs_lon = 130.8797004758756;

% Vytvoř anténní objekt s 2 dBi (např. Half-Wave Dipole z Antenna Toolbox)
ant = dipole;
ant.Tilt = 0;

tx = txsite( ...
    Name = "BS Kitakyushu", ...
    Latitude = bs_lat, ...
    Longitude = bs_lon, ...
    AntennaHeight = 14.5, ...
    TransmitterFrequency = 1.298e9, ...
    TransmitterPower = 39.5, ...
    Antenna = ant);  % přiřazení reálného anténního objektu
show(tx)

% --- 3. Define Ray Tracing Model with Reflections and Weather ---
rtpm = propagationModel("raytracing", ...
    Method = "sbr", ...
    MaxNumReflections = 2, ...
    MaxNumDiffractions = 1, ...
    BuildingsMaterial = "concrete", ...
    TerrainMaterial = "concrete");


% --- 4. Coverage Map with Single-Reflection Paths (1 km radius) ---
clearMap(viewer)
disp("⏳ Spouštím výpočet pokrytí...");
tic;  % start timing
SignalStrengths = -110:5:0;


coverage(tx, rtPlusWeather, ...
    SignalStrengths = SignalStrengths, ...
    MaxRange = 900, ...      % 0.9 km radius
    Resolution = 10, ...
    Transparency = 0.6);

elapsedTime = toc;  % end timing

fprintf("✅ Výpočet pokrytí dokončen za %.2f sekund (%.0f min %.1f s).\n", ...
    elapsedTime, floor(elapsedTime/60), mod(elapsedTime,60));
